# Generated by Django 5.1.6 on 2026-09-02 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('extra_question', models.CharField(blank=True, max_length=160)),
                ('extra_question_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('student_number', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('programme', models.CharField(max_length=80)),
                ('year_of_study', models.CharField(max_length=20)),
                ('extra_answer', models.CharField(blank=True, max_length=240)),
                ('attended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('event', 'student_number')},
            },
        ),
    ]
